### ISSUE TITLE
UI theme for landing page

### ISSUE THREAD

**Issue by Vineet-Sharma29** [Gradient-IIITS/gradient-iiits.github.io#1]
Currently, UI theme for landing page is same as that of blog. We can rather keep different theme for main page and blog. [This](https://themes.gohugo.io/theme/airspace-hugo/) looks good to me. Other themes can also be searched in [modern](https://themes.gohugo.io/tags/modern/) and [landing page](https://themes.gohugo.io/tags/landing-page/) category. Other can give suggestions and vote for the most appropriate theme

**Comment by ram-nad** [comment]
Closing these. Gradient-IIITS/Gradient-s-Blog#7
